### ISSUE TITLE
Migrate to react

### ISSUE THREAD

**Issue by hulien22** [cognitedata/cognite-grafana-datasource#35]
With the release of Grafana 6.0, we can now create plugins via [React instead of AngularJS](http://docs.grafana.org/guides/whats-new-in-v6-0/#react-panels-query-editors).

We should migrate all of our angular code to react as this will make it easier for any future frontend development.

**Comment by polomani** [comment]
We migrated everything that is possible at the moment.
Annotations editor is still on AngularJS, waiting for Grafana to implement it on their side.
Will reopen in Jira when needed
