### ISSUE TITLE
Grafana language documentation

### ISSUE THREAD

**Issue by gzarruk** [cognitedata/cognite-grafana-datasource#58]
Document describing the language used by Grafana for queries and filters. 
Examples will also be useful.

Creating Variables is a very powerful functionality, but given the complexity of the assets and amount of timeseries, complex queries and filtering is required to locate the correct timeseries. 

Example, I have a template dashboard that will have a `variable` that groups all the wells in Valhall and the timeseries under these wells. I need to apply filters to find the correct timeseries for each graph. Using the correct filter is very important to display the correct timeseries. I am not familiar with the Grafana language and it has been a steep learning curve. Having documentation and examples to refer to would be a very useful feature.

**Comment by polomani** [comment]
Hi. could you give an example of what do you mean under "grafana language".
We updated the documentation recently (https://docs.cognite.com/cdf/dashboards/guides/grafana/timeseries.html) and also added some hints inside the plugin itself. Was the issue solved by recently released v2?

**Comment by polomani** [comment]
We have updated the docs quite a lot since 2019, please reach out if you still experience any difficulties.
Also issues have been moved to Jira
