### ISSUE TITLE
Implement Retrying

### ISSUE THREAD

**Issue by hulien22** [cognitedata/cognite-grafana-datasource#63]
It'd be nice to have a way for the data source to automatically retry some failed requests. Would help to mitigate some issues that arise from rate limiting. 
First thoughts are to just implement retrying 5 times with some sort of backoff.

**Comment by hulien22** [comment]
Something to consider here is that if there is a short refreshing value or if the requests take a long time, we may start to have overlapping requests (in which a newer request finishes before an older request and then doesn't get shown). This is already a small issue currently, but does not show up very often.

This means having some sort of cancellation tokens, or keeping track of all requests per row and whether or not there have been newer requests.

**Comment by polomani** [comment]
Rate limits are currently not an issue, especially after the introduction of OIDC tokens.
The ticket will be reopened in Jira if similar issues start happening again.
