### ISSUE TITLE
Event annotations are not working with variables

### ISSUE THREAD

**Issue by pauline1010** [cognitedata/cognite-grafana-datasource#76]
When trying to show events for different values of a variable, the events seems to be global for the dashboard, i.e. they are not corresponding to the chosen variable value. 
It would increase the possibilities a lot if it was possible to filter these on variables as well.

**Comment by hulien22** [comment]
Template variables are supported with events. If you put the variable name (using the typical `$Variable` or `[[Variable]]` format) in the Query or Filter field they will be appropriately replaced with their values.
The main use of this is to have a variable for picking assets, and then for the event, doing something like `event{assetIds=[$Variable], ... }`
