### ISSUE TITLE
Instant queries

### ISSUE THREAD

**Issue by hulien22** [cognitedata/cognite-grafana-datasource#85]
Prometheus and other datasources have a concept of instant queries, which allow users to only fetch the latest datapoint. See https://grafana.com/docs/grafana/latest/features/datasources/prometheus/#instant-queries

There is also a desire to query for the latest value regardless of the selected time range (i.e. even if the dashboard is currently showing metrics from last week, I still want this table/singlestat panel to show the current values)

**Comment by polomani** [comment]
"Last datapoint" has been introduced and is available in the most recent connector version.
