### ISSUE TITLE
Request: Add plugin to the grafana plugins github repository 

### ISSUE THREAD

**Issue by johhat** [cognitedata/cognite-grafana-datasource#9]
Publishing the plugin to the [grafana plugin repository](https://github.com/grafana/grafana-plugin-repository) would make it available in Grafana Cloud. In this manner our customers could use Grafana as a visualization layer in a low-effort via the Grafana Cloud (grafana as a service) solution.

![image](https://user-images.githubusercontent.com/8568753/46952546-719dd200-d08b-11e8-868a-296201d1b5f3.png)
![image](https://user-images.githubusercontent.com/8568753/46952459-300d2700-d08b-11e8-968a-41456310251b.png)

**Comment by hulien22** [comment]
The plugin is now officially on the grafana plugin store: https://grafana.com/plugins/cognitedata-datasource
